//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amusoft.CodeAnalysis.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Amusoft.CodeAnalysis.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all comments from array ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ArrayRuleCodeFixMessage {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ArrayRuleCodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this array. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ArrayRuleDescription {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ArrayRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this array. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ArrayRuleMessageFormat {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ArrayRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this array. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ArrayRuleTitle {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ArrayRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all comments from class ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ClassRuleCodeFixMessage {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ClassRuleCodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this class. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ClassRuleDescription {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ClassRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this class. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ClassRuleMessageFormat {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ClassRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this class. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_ClassRuleTitle {
            get {
                return ResourceManager.GetString("CommentAnalyzer_ClassRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all comments from method ähnelt.
        /// </summary>
        public static string CommentAnalyzer_MethodRuleCodeFixMessage {
            get {
                return ResourceManager.GetString("CommentAnalyzer_MethodRuleCodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this method. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_MethodRuleDescription {
            get {
                return ResourceManager.GetString("CommentAnalyzer_MethodRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this method. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_MethodRuleMessageFormat {
            get {
                return ResourceManager.GetString("CommentAnalyzer_MethodRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this method. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_MethodRuleTitle {
            get {
                return ResourceManager.GetString("CommentAnalyzer_MethodRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all comments from namespace ähnelt.
        /// </summary>
        public static string CommentAnalyzer_NamespaceRuleCodeFixMessage {
            get {
                return ResourceManager.GetString("CommentAnalyzer_NamespaceRuleCodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this namespace. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_NamespaceRuleDescription {
            get {
                return ResourceManager.GetString("CommentAnalyzer_NamespaceRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this namespace. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_NamespaceRuleMessageFormat {
            get {
                return ResourceManager.GetString("CommentAnalyzer_NamespaceRuleMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comments can be removed from this namespace. ähnelt.
        /// </summary>
        public static string CommentAnalyzer_NamespaceRuleTitle {
            get {
                return ResourceManager.GetString("CommentAnalyzer_NamespaceRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delegates execution to collection member of class ähnelt.
        /// </summary>
        public static string DelegateImplementationToFieldAnalyzerDescription {
            get {
                return ResourceManager.GetString("DelegateImplementationToFieldAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forward execution of &quot;{0}&quot; to member &quot;{1}&quot; ähnelt.
        /// </summary>
        public static string DelegateImplementationToFieldAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DelegateImplementationToFieldAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forward execution of member to collection member ähnelt.
        /// </summary>
        public static string DelegateImplementationToFieldAnalyzerTitle {
            get {
                return ResourceManager.GetString("DelegateImplementationToFieldAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate alternate method stub for expression ähnelt.
        /// </summary>
        public static string GenerateMethodFixerMessageFormat {
            get {
                return ResourceManager.GetString("GenerateMethodFixerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string GeneratePocoAnalyzerDescription {
            get {
                return ResourceManager.GetString("GeneratePocoAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string GeneratePocoAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("GeneratePocoAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string GeneratePocoAnalyzerTitle {
            get {
                return ResourceManager.GetString("GeneratePocoAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert method stub similar to &apos;{0}&apos; with return type &apos;{1}&apos; ähnelt.
        /// </summary>
        public static string MessageFormat_CS0123_FixByInsertingMethodStub_0_1 {
            get {
                return ResourceManager.GetString("MessageFormat_CS0123_FixByInsertingMethodStub_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alter parameter types of &apos;{0}&apos; to match expected signature ähnelt.
        /// </summary>
        public static string MessageFormat_CS0123_FixByRewritingParameters_0 {
            get {
                return ResourceManager.GetString("MessageFormat_CS0123_FixByRewritingParameters_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die throw new NotImplementedException(); ähnelt.
        /// </summary>
        public static string MessageFormat_CS0161_FixByReplacingWithThrowExpression {
            get {
                return ResourceManager.GetString("MessageFormat_CS0161_FixByReplacingWithThrowExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alter return type of &apos;{0}&apos; to &apos;{1}&apos; ähnelt.
        /// </summary>
        public static string MessageFormat_CS0407_FixByRewritingReturnType_0_1_2 {
            get {
                return ResourceManager.GetString("MessageFormat_CS0407_FixByRewritingReturnType_0_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrap method exit points in Task.FromResult() ähnelt.
        /// </summary>
        public static string MessageFormat_CS1998_FixByWrappingInTaskResult {
            get {
                return ResourceManager.GetString("MessageFormat_CS1998_FixByWrappingInTaskResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unwrap Task.FromResult(); ähnelt.
        /// </summary>
        public static string MessageFormat_CS4016_FixByUnwrappingTaskFromResult {
            get {
                return ResourceManager.GetString("MessageFormat_CS4016_FixByUnwrappingTaskFromResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string ResxEntryAnalyzerDescription {
            get {
                return ResourceManager.GetString("ResxEntryAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string ResxEntryAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ResxEntryAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string ResxEntryAnalyzerTitle {
            get {
                return ResourceManager.GetString("ResxEntryAnalyzerTitle", resourceCulture);
            }
        }
    }
}
